[package]
name = "nmux-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "nmux"
path = "src/bin/nmux.rs"

[[bin]]
name = "nmuxd"
path = "src/bin/nmuxd.rs"

[features]
libghostty-vt = ["nmux-core/libghostty-vt"]

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
flatbuffers = "=25.12.19"
libc = "0.2"
nmux-core = { path = "../nmux-core" }
nmux-proto = { path = "../nmux-proto" }
