[workspace]
members = [
  "crates/nmux-cli",
  "crates/nmux-core",
  "crates/nmux-proto",
  "crates/xtask",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ahimsalabs/nmux"

[workspace.dependencies]
flatbuffers = "=25.12.19"
libc = "0.2"
portable-pty = "0.9.0"
serde_json = "1"
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
clap = { version = "4.6.1", features = ["derive"] }
crossterm = "0.29"
nmux-proto = { path = "crates/nmux-proto" }
nmux-core = { path = "crates/nmux-core", default-features = false }
