[package]
name = "nmux-core"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
libghostty-vt = ["dep:libghostty-vt", "libghostty-vt/link-static"]

[dependencies]
flatbuffers = "=25.12.19"
libc = "0.2"
libghostty-vt = { git = "https://github.com/uzaaft/libghostty-rs.git", rev = "31d1f70004ff80727e36437cd540984f927333ce", optional = true }
nmux-proto = { path = "../nmux-proto" }
portable-pty = "0.9.0"

[dev-dependencies]
serde_json = "1"
