// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CellRun struct {
	_tab flatbuffers.Table
}

func GetRootAsCellRun(buf []byte, offset flatbuffers.UOffsetT) *CellRun {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CellRun{}
	x.Init(buf, n+offset)
	return x
}

func FinishCellRunBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCellRun(buf []byte, offset flatbuffers.UOffsetT) *CellRun {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CellRun{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCellRunBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CellRun) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CellRun) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CellRun) TextUtf8() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CellRun) CellWidths(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *CellRun) CellWidthsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *CellRun) CellWidthsBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CellRun) MutateCellWidths(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *CellRun) StyleId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CellRun) MutateStyleId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *CellRun) Flags() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CellRun) MutateFlags(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func (rcv *CellRun) HyperlinkId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CellRun) MutateHyperlinkId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

func CellRunStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func CellRunAddTextUtf8(builder *flatbuffers.Builder, textUtf8 flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(textUtf8), 0)
}
func CellRunAddCellWidths(builder *flatbuffers.Builder, cellWidths flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(cellWidths), 0)
}
func CellRunStartCellWidthsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func CellRunAddStyleId(builder *flatbuffers.Builder, styleId uint32) {
	builder.PrependUint32Slot(2, styleId, 0)
}
func CellRunAddFlags(builder *flatbuffers.Builder, flags uint32) {
	builder.PrependUint32Slot(3, flags, 0)
}
func CellRunAddHyperlinkId(builder *flatbuffers.Builder, hyperlinkId uint32) {
	builder.PrependUint32Slot(4, hyperlinkId, 0)
}
func CellRunEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
