// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CursorState struct {
	_tab flatbuffers.Table
}

func GetRootAsCursorState(buf []byte, offset flatbuffers.UOffsetT) *CursorState {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CursorState{}
	x.Init(buf, n+offset)
	return x
}

func FinishCursorStateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCursorState(buf []byte, offset flatbuffers.UOffsetT) *CursorState {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CursorState{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCursorStateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CursorState) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CursorState) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CursorState) Row() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CursorState) MutateRow(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *CursorState) Col() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CursorState) MutateCol(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *CursorState) Visible() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return true
}

func (rcv *CursorState) MutateVisible(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func (rcv *CursorState) Shape() CursorShape {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return CursorShape(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *CursorState) MutateShape(n CursorShape) bool {
	return rcv._tab.MutateInt8Slot(10, int8(n))
}

func CursorStateStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func CursorStateAddRow(builder *flatbuffers.Builder, row uint32) {
	builder.PrependUint32Slot(0, row, 0)
}
func CursorStateAddCol(builder *flatbuffers.Builder, col uint32) {
	builder.PrependUint32Slot(1, col, 0)
}
func CursorStateAddVisible(builder *flatbuffers.Builder, visible bool) {
	builder.PrependBoolSlot(2, visible, true)
}
func CursorStateAddShape(builder *flatbuffers.Builder, shape CursorShape) {
	builder.PrependInt8Slot(3, int8(shape), 0)
}
func CursorStateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
