// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type CursorShape int8

const (
	CursorShapeBlock     CursorShape = 0
	CursorShapeBeam      CursorShape = 1
	CursorShapeUnderline CursorShape = 2
)

var EnumNamesCursorShape = map[CursorShape]string{
	CursorShapeBlock:     "Block",
	CursorShapeBeam:      "Beam",
	CursorShapeUnderline: "Underline",
}

var EnumValuesCursorShape = map[string]CursorShape{
	"Block":     CursorShapeBlock,
	"Beam":      CursorShapeBeam,
	"Underline": CursorShapeUnderline,
}

func (v CursorShape) String() string {
	if s, ok := EnumNamesCursorShape[v]; ok {
		return s
	}
	return "CursorShape(" + strconv.FormatInt(int64(v), 10) + ")"
}
