// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type EnvelopeBody byte

const (
	EnvelopeBodyNONE                  EnvelopeBody = 0
	EnvelopeBodyWorkspaceTreeSnapshot EnvelopeBody = 1
	EnvelopeBodyPaneSurfaceSnapshot   EnvelopeBody = 2
	EnvelopeBodyPaneSurfacePatch      EnvelopeBody = 3
	EnvelopeBodyInputEvent            EnvelopeBody = 4
	EnvelopeBodyResizeIntent          EnvelopeBody = 5
	EnvelopeBodyError                 EnvelopeBody = 6
)

var EnumNamesEnvelopeBody = map[EnvelopeBody]string{
	EnvelopeBodyNONE:                  "NONE",
	EnvelopeBodyWorkspaceTreeSnapshot: "WorkspaceTreeSnapshot",
	EnvelopeBodyPaneSurfaceSnapshot:   "PaneSurfaceSnapshot",
	EnvelopeBodyPaneSurfacePatch:      "PaneSurfacePatch",
	EnvelopeBodyInputEvent:            "InputEvent",
	EnvelopeBodyResizeIntent:          "ResizeIntent",
	EnvelopeBodyError:                 "Error",
}

var EnumValuesEnvelopeBody = map[string]EnvelopeBody{
	"NONE":                  EnvelopeBodyNONE,
	"WorkspaceTreeSnapshot": EnvelopeBodyWorkspaceTreeSnapshot,
	"PaneSurfaceSnapshot":   EnvelopeBodyPaneSurfaceSnapshot,
	"PaneSurfacePatch":      EnvelopeBodyPaneSurfacePatch,
	"InputEvent":            EnvelopeBodyInputEvent,
	"ResizeIntent":          EnvelopeBodyResizeIntent,
	"Error":                 EnvelopeBodyError,
}

func (v EnvelopeBody) String() string {
	if s, ok := EnumNamesEnvelopeBody[v]; ok {
		return s
	}
	return "EnvelopeBody(" + strconv.FormatInt(int64(v), 10) + ")"
}
