// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Envelope struct {
	_tab flatbuffers.Table
}

func GetRootAsEnvelope(buf []byte, offset flatbuffers.UOffsetT) *Envelope {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Envelope{}
	x.Init(buf, n+offset)
	return x
}

func FinishEnvelopeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEnvelope(buf []byte, offset flatbuffers.UOffsetT) *Envelope {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Envelope{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEnvelopeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Envelope) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Envelope) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Envelope) ProtocolVersion() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Envelope) MutateProtocolVersion(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *Envelope) SessionId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Envelope) ConnectionId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Envelope) Seq() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Envelope) MutateSeq(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *Envelope) Ack() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Envelope) MutateAck(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func (rcv *Envelope) SentAtMonoMs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Envelope) MutateSentAtMonoMs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(14, n)
}

func (rcv *Envelope) BodyType() EnvelopeBody {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return EnvelopeBody(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Envelope) MutateBodyType(n EnvelopeBody) bool {
	return rcv._tab.MutateByteSlot(16, byte(n))
}

func (rcv *Envelope) Body(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func EnvelopeStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func EnvelopeAddProtocolVersion(builder *flatbuffers.Builder, protocolVersion uint32) {
	builder.PrependUint32Slot(0, protocolVersion, 0)
}
func EnvelopeAddSessionId(builder *flatbuffers.Builder, sessionId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(sessionId), 0)
}
func EnvelopeAddConnectionId(builder *flatbuffers.Builder, connectionId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(connectionId), 0)
}
func EnvelopeAddSeq(builder *flatbuffers.Builder, seq uint64) {
	builder.PrependUint64Slot(3, seq, 0)
}
func EnvelopeAddAck(builder *flatbuffers.Builder, ack uint64) {
	builder.PrependUint64Slot(4, ack, 0)
}
func EnvelopeAddSentAtMonoMs(builder *flatbuffers.Builder, sentAtMonoMs uint64) {
	builder.PrependUint64Slot(5, sentAtMonoMs, 0)
}
func EnvelopeAddBodyType(builder *flatbuffers.Builder, bodyType EnvelopeBody) {
	builder.PrependByteSlot(6, byte(bodyType), 0)
}
func EnvelopeAddBody(builder *flatbuffers.Builder, body flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(body), 0)
}
func EnvelopeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
