// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type ErrorCode uint16

const (
	ErrorCodeUnknown                    ErrorCode = 0
	ErrorCodeProtocolVersionUnsupported ErrorCode = 1
	ErrorCodeSessionNotFound            ErrorCode = 2
	ErrorCodePaneNotFound               ErrorCode = 3
	ErrorCodePermissionDenied           ErrorCode = 4
	ErrorCodeStaleVersion               ErrorCode = 5
)

var EnumNamesErrorCode = map[ErrorCode]string{
	ErrorCodeUnknown:                    "Unknown",
	ErrorCodeProtocolVersionUnsupported: "ProtocolVersionUnsupported",
	ErrorCodeSessionNotFound:            "SessionNotFound",
	ErrorCodePaneNotFound:               "PaneNotFound",
	ErrorCodePermissionDenied:           "PermissionDenied",
	ErrorCodeStaleVersion:               "StaleVersion",
}

var EnumValuesErrorCode = map[string]ErrorCode{
	"Unknown":                    ErrorCodeUnknown,
	"ProtocolVersionUnsupported": ErrorCodeProtocolVersionUnsupported,
	"SessionNotFound":            ErrorCodeSessionNotFound,
	"PaneNotFound":               ErrorCodePaneNotFound,
	"PermissionDenied":           ErrorCodePermissionDenied,
	"StaleVersion":               ErrorCodeStaleVersion,
}

func (v ErrorCode) String() string {
	if s, ok := EnumNamesErrorCode[v]; ok {
		return s
	}
	return "ErrorCode(" + strconv.FormatInt(int64(v), 10) + ")"
}
