// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type InputKind int8

const (
	InputKindKey   InputKind = 0
	InputKindMouse InputKind = 1
	InputKindPaste InputKind = 2
)

var EnumNamesInputKind = map[InputKind]string{
	InputKindKey:   "Key",
	InputKindMouse: "Mouse",
	InputKindPaste: "Paste",
}

var EnumValuesInputKind = map[string]InputKind{
	"Key":   InputKindKey,
	"Mouse": InputKindMouse,
	"Paste": InputKindPaste,
}

func (v InputKind) String() string {
	if s, ok := EnumNamesInputKind[v]; ok {
		return s
	}
	return "InputKind(" + strconv.FormatInt(int64(v), 10) + ")"
}
