// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type InputEvent struct {
	_tab flatbuffers.Table
}

func GetRootAsInputEvent(buf []byte, offset flatbuffers.UOffsetT) *InputEvent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InputEvent{}
	x.Init(buf, n+offset)
	return x
}

func FinishInputEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsInputEvent(buf []byte, offset flatbuffers.UOffsetT) *InputEvent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &InputEvent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedInputEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *InputEvent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InputEvent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *InputEvent) PaneId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InputEvent) ActorId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InputEvent) InputSeq() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InputEvent) MutateInputSeq(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *InputEvent) Kind() InputKind {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return InputKind(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *InputEvent) MutateKind(n InputKind) bool {
	return rcv._tab.MutateInt8Slot(10, int8(n))
}

func (rcv *InputEvent) Key(obj *KeyInput) *KeyInput {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(KeyInput)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *InputEvent) Mouse(obj *MouseInput) *MouseInput {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(MouseInput)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *InputEvent) Paste(obj *PasteInput) *PasteInput {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(PasteInput)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func InputEventStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func InputEventAddPaneId(builder *flatbuffers.Builder, paneId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(paneId), 0)
}
func InputEventAddActorId(builder *flatbuffers.Builder, actorId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(actorId), 0)
}
func InputEventAddInputSeq(builder *flatbuffers.Builder, inputSeq uint64) {
	builder.PrependUint64Slot(2, inputSeq, 0)
}
func InputEventAddKind(builder *flatbuffers.Builder, kind InputKind) {
	builder.PrependInt8Slot(3, int8(kind), 0)
}
func InputEventAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(key), 0)
}
func InputEventAddMouse(builder *flatbuffers.Builder, mouse flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(mouse), 0)
}
func InputEventAddPaste(builder *flatbuffers.Builder, paste flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(paste), 0)
}
func InputEventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
