// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type KeyInput struct {
	_tab flatbuffers.Table
}

func GetRootAsKeyInput(buf []byte, offset flatbuffers.UOffsetT) *KeyInput {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &KeyInput{}
	x.Init(buf, n+offset)
	return x
}

func FinishKeyInputBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsKeyInput(buf []byte, offset flatbuffers.UOffsetT) *KeyInput {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &KeyInput{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedKeyInputBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *KeyInput) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KeyInput) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *KeyInput) TextUtf8() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *KeyInput) KeyName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *KeyInput) Modifiers() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *KeyInput) MutateModifiers(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func KeyInputStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func KeyInputAddTextUtf8(builder *flatbuffers.Builder, textUtf8 flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(textUtf8), 0)
}
func KeyInputAddKeyName(builder *flatbuffers.Builder, keyName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(keyName), 0)
}
func KeyInputAddModifiers(builder *flatbuffers.Builder, modifiers uint32) {
	builder.PrependUint32Slot(2, modifiers, 0)
}
func KeyInputEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
