// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MouseInput struct {
	_tab flatbuffers.Table
}

func GetRootAsMouseInput(buf []byte, offset flatbuffers.UOffsetT) *MouseInput {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MouseInput{}
	x.Init(buf, n+offset)
	return x
}

func FinishMouseInputBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMouseInput(buf []byte, offset flatbuffers.UOffsetT) *MouseInput {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MouseInput{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMouseInputBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MouseInput) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MouseInput) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MouseInput) Row() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MouseInput) MutateRow(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *MouseInput) Col() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MouseInput) MutateCol(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *MouseInput) Button() MouseButton {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return MouseButton(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *MouseInput) MutateButton(n MouseButton) bool {
	return rcv._tab.MutateInt8Slot(8, int8(n))
}

func (rcv *MouseInput) Modifiers() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MouseInput) MutateModifiers(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func MouseInputStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func MouseInputAddRow(builder *flatbuffers.Builder, row uint32) {
	builder.PrependUint32Slot(0, row, 0)
}
func MouseInputAddCol(builder *flatbuffers.Builder, col uint32) {
	builder.PrependUint32Slot(1, col, 0)
}
func MouseInputAddButton(builder *flatbuffers.Builder, button MouseButton) {
	builder.PrependInt8Slot(2, int8(button), 0)
}
func MouseInputAddModifiers(builder *flatbuffers.Builder, modifiers uint32) {
	builder.PrependUint32Slot(3, modifiers, 0)
}
func MouseInputEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
