// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type MouseButton int8

const (
	MouseButtonNone      MouseButton = 0
	MouseButtonLeft      MouseButton = 1
	MouseButtonMiddle    MouseButton = 2
	MouseButtonRight     MouseButton = 3
	MouseButtonWheelUp   MouseButton = 4
	MouseButtonWheelDown MouseButton = 5
)

var EnumNamesMouseButton = map[MouseButton]string{
	MouseButtonNone:      "None",
	MouseButtonLeft:      "Left",
	MouseButtonMiddle:    "Middle",
	MouseButtonRight:     "Right",
	MouseButtonWheelUp:   "WheelUp",
	MouseButtonWheelDown: "WheelDown",
}

var EnumValuesMouseButton = map[string]MouseButton{
	"None":      MouseButtonNone,
	"Left":      MouseButtonLeft,
	"Middle":    MouseButtonMiddle,
	"Right":     MouseButtonRight,
	"WheelUp":   MouseButtonWheelUp,
	"WheelDown": MouseButtonWheelDown,
}

func (v MouseButton) String() string {
	if s, ok := EnumNamesMouseButton[v]; ok {
		return s
	}
	return "MouseButton(" + strconv.FormatInt(int64(v), 10) + ")"
}
