// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type PaneKind int8

const (
	PaneKindPty     PaneKind = 0
	PaneKindAdapter PaneKind = 1
)

var EnumNamesPaneKind = map[PaneKind]string{
	PaneKindPty:     "Pty",
	PaneKindAdapter: "Adapter",
}

var EnumValuesPaneKind = map[string]PaneKind{
	"Pty":     PaneKindPty,
	"Adapter": PaneKindAdapter,
}

func (v PaneKind) String() string {
	if s, ok := EnumNamesPaneKind[v]; ok {
		return s
	}
	return "PaneKind(" + strconv.FormatInt(int64(v), 10) + ")"
}
