// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PaneSurfaceSnapshot struct {
	_tab flatbuffers.Table
}

func GetRootAsPaneSurfaceSnapshot(buf []byte, offset flatbuffers.UOffsetT) *PaneSurfaceSnapshot {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PaneSurfaceSnapshot{}
	x.Init(buf, n+offset)
	return x
}

func FinishPaneSurfaceSnapshotBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPaneSurfaceSnapshot(buf []byte, offset flatbuffers.UOffsetT) *PaneSurfaceSnapshot {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PaneSurfaceSnapshot{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPaneSurfaceSnapshotBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PaneSurfaceSnapshot) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PaneSurfaceSnapshot) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PaneSurfaceSnapshot) PaneId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PaneSurfaceSnapshot) Version() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PaneSurfaceSnapshot) MutateVersion(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *PaneSurfaceSnapshot) Surface() SurfaceKind {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return SurfaceKind(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *PaneSurfaceSnapshot) MutateSurface(n SurfaceKind) bool {
	return rcv._tab.MutateInt8Slot(8, int8(n))
}

func (rcv *PaneSurfaceSnapshot) Cols() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PaneSurfaceSnapshot) MutateCols(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func (rcv *PaneSurfaceSnapshot) Rows() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PaneSurfaceSnapshot) MutateRows(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

func (rcv *PaneSurfaceSnapshot) Cursor(obj *CursorState) *CursorState {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(CursorState)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *PaneSurfaceSnapshot) Styles(obj *Style, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *PaneSurfaceSnapshot) StylesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *PaneSurfaceSnapshot) RowsData(obj *SurfaceRow, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *PaneSurfaceSnapshot) RowsDataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func PaneSurfaceSnapshotStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func PaneSurfaceSnapshotAddPaneId(builder *flatbuffers.Builder, paneId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(paneId), 0)
}
func PaneSurfaceSnapshotAddVersion(builder *flatbuffers.Builder, version uint64) {
	builder.PrependUint64Slot(1, version, 0)
}
func PaneSurfaceSnapshotAddSurface(builder *flatbuffers.Builder, surface SurfaceKind) {
	builder.PrependInt8Slot(2, int8(surface), 0)
}
func PaneSurfaceSnapshotAddCols(builder *flatbuffers.Builder, cols uint32) {
	builder.PrependUint32Slot(3, cols, 0)
}
func PaneSurfaceSnapshotAddRows(builder *flatbuffers.Builder, rows uint32) {
	builder.PrependUint32Slot(4, rows, 0)
}
func PaneSurfaceSnapshotAddCursor(builder *flatbuffers.Builder, cursor flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(cursor), 0)
}
func PaneSurfaceSnapshotAddStyles(builder *flatbuffers.Builder, styles flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(styles), 0)
}
func PaneSurfaceSnapshotStartStylesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PaneSurfaceSnapshotAddRowsData(builder *flatbuffers.Builder, rowsData flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(rowsData), 0)
}
func PaneSurfaceSnapshotStartRowsDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PaneSurfaceSnapshotEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
