// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PaneNode struct {
	_tab flatbuffers.Table
}

func GetRootAsPaneNode(buf []byte, offset flatbuffers.UOffsetT) *PaneNode {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PaneNode{}
	x.Init(buf, n+offset)
	return x
}

func FinishPaneNodeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPaneNode(buf []byte, offset flatbuffers.UOffsetT) *PaneNode {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PaneNode{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPaneNodeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PaneNode) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PaneNode) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PaneNode) PaneId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PaneNode) Kind() PaneKind {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return PaneKind(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *PaneNode) MutateKind(n PaneKind) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

func (rcv *PaneNode) SplitAxis() SplitAxis {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return SplitAxis(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *PaneNode) MutateSplitAxis(n SplitAxis) bool {
	return rcv._tab.MutateInt8Slot(8, int8(n))
}

func (rcv *PaneNode) Children(obj *PaneNode, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *PaneNode) ChildrenLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *PaneNode) SurfaceVersion() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PaneNode) MutateSurfaceVersion(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func (rcv *PaneNode) Cols() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PaneNode) MutateCols(n uint32) bool {
	return rcv._tab.MutateUint32Slot(14, n)
}

func (rcv *PaneNode) Rows() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PaneNode) MutateRows(n uint32) bool {
	return rcv._tab.MutateUint32Slot(16, n)
}

func (rcv *PaneNode) ResizePolicy() ResizePolicy {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return ResizePolicy(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *PaneNode) MutateResizePolicy(n ResizePolicy) bool {
	return rcv._tab.MutateInt8Slot(18, int8(n))
}

func PaneNodeStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func PaneNodeAddPaneId(builder *flatbuffers.Builder, paneId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(paneId), 0)
}
func PaneNodeAddKind(builder *flatbuffers.Builder, kind PaneKind) {
	builder.PrependInt8Slot(1, int8(kind), 0)
}
func PaneNodeAddSplitAxis(builder *flatbuffers.Builder, splitAxis SplitAxis) {
	builder.PrependInt8Slot(2, int8(splitAxis), 0)
}
func PaneNodeAddChildren(builder *flatbuffers.Builder, children flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(children), 0)
}
func PaneNodeStartChildrenVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PaneNodeAddSurfaceVersion(builder *flatbuffers.Builder, surfaceVersion uint64) {
	builder.PrependUint64Slot(4, surfaceVersion, 0)
}
func PaneNodeAddCols(builder *flatbuffers.Builder, cols uint32) {
	builder.PrependUint32Slot(5, cols, 0)
}
func PaneNodeAddRows(builder *flatbuffers.Builder, rows uint32) {
	builder.PrependUint32Slot(6, rows, 0)
}
func PaneNodeAddResizePolicy(builder *flatbuffers.Builder, resizePolicy ResizePolicy) {
	builder.PrependInt8Slot(7, int8(resizePolicy), 0)
}
func PaneNodeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
