// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PaneSurfacePatch struct {
	_tab flatbuffers.Table
}

func GetRootAsPaneSurfacePatch(buf []byte, offset flatbuffers.UOffsetT) *PaneSurfacePatch {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PaneSurfacePatch{}
	x.Init(buf, n+offset)
	return x
}

func FinishPaneSurfacePatchBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPaneSurfacePatch(buf []byte, offset flatbuffers.UOffsetT) *PaneSurfacePatch {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PaneSurfacePatch{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPaneSurfacePatchBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PaneSurfacePatch) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PaneSurfacePatch) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PaneSurfacePatch) PaneId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PaneSurfacePatch) BaseVersion() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PaneSurfacePatch) MutateBaseVersion(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *PaneSurfacePatch) Version() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PaneSurfacePatch) MutateVersion(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *PaneSurfacePatch) Kind() PatchKind {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return PatchKind(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *PaneSurfacePatch) MutateKind(n PatchKind) bool {
	return rcv._tab.MutateInt8Slot(10, int8(n))
}

func (rcv *PaneSurfacePatch) RowUpdates(obj *RowUpdate, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *PaneSurfacePatch) RowUpdatesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *PaneSurfacePatch) Cursor(obj *CursorState) *CursorState {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(CursorState)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func PaneSurfacePatchStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func PaneSurfacePatchAddPaneId(builder *flatbuffers.Builder, paneId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(paneId), 0)
}
func PaneSurfacePatchAddBaseVersion(builder *flatbuffers.Builder, baseVersion uint64) {
	builder.PrependUint64Slot(1, baseVersion, 0)
}
func PaneSurfacePatchAddVersion(builder *flatbuffers.Builder, version uint64) {
	builder.PrependUint64Slot(2, version, 0)
}
func PaneSurfacePatchAddKind(builder *flatbuffers.Builder, kind PatchKind) {
	builder.PrependInt8Slot(3, int8(kind), 0)
}
func PaneSurfacePatchAddRowUpdates(builder *flatbuffers.Builder, rowUpdates flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(rowUpdates), 0)
}
func PaneSurfacePatchStartRowUpdatesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PaneSurfacePatchAddCursor(builder *flatbuffers.Builder, cursor flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(cursor), 0)
}
func PaneSurfacePatchEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
