// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PasteInput struct {
	_tab flatbuffers.Table
}

func GetRootAsPasteInput(buf []byte, offset flatbuffers.UOffsetT) *PasteInput {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PasteInput{}
	x.Init(buf, n+offset)
	return x
}

func FinishPasteInputBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPasteInput(buf []byte, offset flatbuffers.UOffsetT) *PasteInput {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PasteInput{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPasteInputBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PasteInput) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PasteInput) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PasteInput) TextUtf8() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PasteInput) Bracketed() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return true
}

func (rcv *PasteInput) MutateBracketed(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func PasteInputStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PasteInputAddTextUtf8(builder *flatbuffers.Builder, textUtf8 flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(textUtf8), 0)
}
func PasteInputAddBracketed(builder *flatbuffers.Builder, bracketed bool) {
	builder.PrependBoolSlot(1, bracketed, true)
}
func PasteInputEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
