// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type PatchKind int8

const (
	PatchKindReplaceRows         PatchKind = 0
	PatchKindCursorOnly          PatchKind = 1
	PatchKindModeOnly            PatchKind = 2
	PatchKindFullRefreshRequired PatchKind = 3
)

var EnumNamesPatchKind = map[PatchKind]string{
	PatchKindReplaceRows:         "ReplaceRows",
	PatchKindCursorOnly:          "CursorOnly",
	PatchKindModeOnly:            "ModeOnly",
	PatchKindFullRefreshRequired: "FullRefreshRequired",
}

var EnumValuesPatchKind = map[string]PatchKind{
	"ReplaceRows":         PatchKindReplaceRows,
	"CursorOnly":          PatchKindCursorOnly,
	"ModeOnly":            PatchKindModeOnly,
	"FullRefreshRequired": PatchKindFullRefreshRequired,
}

func (v PatchKind) String() string {
	if s, ok := EnumNamesPatchKind[v]; ok {
		return s
	}
	return "PatchKind(" + strconv.FormatInt(int64(v), 10) + ")"
}
