// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type ResizePolicy int8

const (
	ResizePolicyFixed        ResizePolicy = 0
	ResizePolicyLeader       ResizePolicy = 1
	ResizePolicyActiveClient ResizePolicy = 2
	ResizePolicyManual       ResizePolicy = 3
)

var EnumNamesResizePolicy = map[ResizePolicy]string{
	ResizePolicyFixed:        "Fixed",
	ResizePolicyLeader:       "Leader",
	ResizePolicyActiveClient: "ActiveClient",
	ResizePolicyManual:       "Manual",
}

var EnumValuesResizePolicy = map[string]ResizePolicy{
	"Fixed":        ResizePolicyFixed,
	"Leader":       ResizePolicyLeader,
	"ActiveClient": ResizePolicyActiveClient,
	"Manual":       ResizePolicyManual,
}

func (v ResizePolicy) String() string {
	if s, ok := EnumNamesResizePolicy[v]; ok {
		return s
	}
	return "ResizePolicy(" + strconv.FormatInt(int64(v), 10) + ")"
}
