// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ResizeIntent struct {
	_tab flatbuffers.Table
}

func GetRootAsResizeIntent(buf []byte, offset flatbuffers.UOffsetT) *ResizeIntent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ResizeIntent{}
	x.Init(buf, n+offset)
	return x
}

func FinishResizeIntentBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsResizeIntent(buf []byte, offset flatbuffers.UOffsetT) *ResizeIntent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ResizeIntent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedResizeIntentBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ResizeIntent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ResizeIntent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ResizeIntent) PaneId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ResizeIntent) ActorId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ResizeIntent) DesiredCols() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ResizeIntent) MutateDesiredCols(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *ResizeIntent) DesiredRows() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ResizeIntent) MutateDesiredRows(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func (rcv *ResizeIntent) Reason() ResizeReason {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return ResizeReason(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ResizeIntent) MutateReason(n ResizeReason) bool {
	return rcv._tab.MutateInt8Slot(12, int8(n))
}

func ResizeIntentStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func ResizeIntentAddPaneId(builder *flatbuffers.Builder, paneId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(paneId), 0)
}
func ResizeIntentAddActorId(builder *flatbuffers.Builder, actorId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(actorId), 0)
}
func ResizeIntentAddDesiredCols(builder *flatbuffers.Builder, desiredCols uint32) {
	builder.PrependUint32Slot(2, desiredCols, 0)
}
func ResizeIntentAddDesiredRows(builder *flatbuffers.Builder, desiredRows uint32) {
	builder.PrependUint32Slot(3, desiredRows, 0)
}
func ResizeIntentAddReason(builder *flatbuffers.Builder, reason ResizeReason) {
	builder.PrependInt8Slot(4, int8(reason), 0)
}
func ResizeIntentEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
