// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type ResizeReason int8

const (
	ResizeReasonFrontendViewport ResizeReason = 0
	ResizeReasonUserCommand      ResizeReason = 1
	ResizeReasonAttach           ResizeReason = 2
	ResizeReasonPolicy           ResizeReason = 3
)

var EnumNamesResizeReason = map[ResizeReason]string{
	ResizeReasonFrontendViewport: "FrontendViewport",
	ResizeReasonUserCommand:      "UserCommand",
	ResizeReasonAttach:           "Attach",
	ResizeReasonPolicy:           "Policy",
}

var EnumValuesResizeReason = map[string]ResizeReason{
	"FrontendViewport": ResizeReasonFrontendViewport,
	"UserCommand":      ResizeReasonUserCommand,
	"Attach":           ResizeReasonAttach,
	"Policy":           ResizeReasonPolicy,
}

func (v ResizeReason) String() string {
	if s, ok := EnumNamesResizeReason[v]; ok {
		return s
	}
	return "ResizeReason(" + strconv.FormatInt(int64(v), 10) + ")"
}
