// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RowUpdate struct {
	_tab flatbuffers.Table
}

func GetRootAsRowUpdate(buf []byte, offset flatbuffers.UOffsetT) *RowUpdate {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RowUpdate{}
	x.Init(buf, n+offset)
	return x
}

func FinishRowUpdateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRowUpdate(buf []byte, offset flatbuffers.UOffsetT) *RowUpdate {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RowUpdate{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRowUpdateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RowUpdate) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RowUpdate) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RowUpdate) Row() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RowUpdate) MutateRow(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *RowUpdate) Runs(obj *CellRun, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *RowUpdate) RunsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *RowUpdate) DirtyHash() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RowUpdate) MutateDirtyHash(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func RowUpdateStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func RowUpdateAddRow(builder *flatbuffers.Builder, row uint32) {
	builder.PrependUint32Slot(0, row, 0)
}
func RowUpdateAddRuns(builder *flatbuffers.Builder, runs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(runs), 0)
}
func RowUpdateStartRunsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func RowUpdateAddDirtyHash(builder *flatbuffers.Builder, dirtyHash uint64) {
	builder.PrependUint64Slot(2, dirtyHash, 0)
}
func RowUpdateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
