// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type SplitAxis int8

const (
	SplitAxisNone       SplitAxis = 0
	SplitAxisHorizontal SplitAxis = 1
	SplitAxisVertical   SplitAxis = 2
)

var EnumNamesSplitAxis = map[SplitAxis]string{
	SplitAxisNone:       "None",
	SplitAxisHorizontal: "Horizontal",
	SplitAxisVertical:   "Vertical",
}

var EnumValuesSplitAxis = map[string]SplitAxis{
	"None":       SplitAxisNone,
	"Horizontal": SplitAxisHorizontal,
	"Vertical":   SplitAxisVertical,
}

func (v SplitAxis) String() string {
	if s, ok := EnumNamesSplitAxis[v]; ok {
		return s
	}
	return "SplitAxis(" + strconv.FormatInt(int64(v), 10) + ")"
}
