// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Style struct {
	_tab flatbuffers.Table
}

func GetRootAsStyle(buf []byte, offset flatbuffers.UOffsetT) *Style {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Style{}
	x.Init(buf, n+offset)
	return x
}

func FinishStyleBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStyle(buf []byte, offset flatbuffers.UOffsetT) *Style {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Style{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStyleBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Style) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Style) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Style) FgRgba() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Style) MutateFgRgba(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *Style) BgRgba() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Style) MutateBgRgba(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *Style) UnderlineRgba() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Style) MutateUnderlineRgba(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *Style) Flags() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Style) MutateFlags(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func StyleStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func StyleAddFgRgba(builder *flatbuffers.Builder, fgRgba uint32) {
	builder.PrependUint32Slot(0, fgRgba, 0)
}
func StyleAddBgRgba(builder *flatbuffers.Builder, bgRgba uint32) {
	builder.PrependUint32Slot(1, bgRgba, 0)
}
func StyleAddUnderlineRgba(builder *flatbuffers.Builder, underlineRgba uint32) {
	builder.PrependUint32Slot(2, underlineRgba, 0)
}
func StyleAddFlags(builder *flatbuffers.Builder, flags uint32) {
	builder.PrependUint32Slot(3, flags, 0)
}
func StyleEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
