// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SurfaceRow struct {
	_tab flatbuffers.Table
}

func GetRootAsSurfaceRow(buf []byte, offset flatbuffers.UOffsetT) *SurfaceRow {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SurfaceRow{}
	x.Init(buf, n+offset)
	return x
}

func FinishSurfaceRowBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSurfaceRow(buf []byte, offset flatbuffers.UOffsetT) *SurfaceRow {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SurfaceRow{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSurfaceRowBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SurfaceRow) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SurfaceRow) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SurfaceRow) Row() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SurfaceRow) MutateRow(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *SurfaceRow) Runs(obj *CellRun, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SurfaceRow) RunsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SurfaceRow) DirtyHash() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SurfaceRow) MutateDirtyHash(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func SurfaceRowStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func SurfaceRowAddRow(builder *flatbuffers.Builder, row uint32) {
	builder.PrependUint32Slot(0, row, 0)
}
func SurfaceRowAddRuns(builder *flatbuffers.Builder, runs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(runs), 0)
}
func SurfaceRowStartRunsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SurfaceRowAddDirtyHash(builder *flatbuffers.Builder, dirtyHash uint64) {
	builder.PrependUint64Slot(2, dirtyHash, 0)
}
func SurfaceRowEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
