// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import "strconv"

type SurfaceKind int8

const (
	SurfaceKindMain      SurfaceKind = 0
	SurfaceKindAlternate SurfaceKind = 1
)

var EnumNamesSurfaceKind = map[SurfaceKind]string{
	SurfaceKindMain:      "Main",
	SurfaceKindAlternate: "Alternate",
}

var EnumValuesSurfaceKind = map[string]SurfaceKind{
	"Main":      SurfaceKindMain,
	"Alternate": SurfaceKindAlternate,
}

func (v SurfaceKind) String() string {
	if s, ok := EnumNamesSurfaceKind[v]; ok {
		return s
	}
	return "SurfaceKind(" + strconv.FormatInt(int64(v), 10) + ")"
}
