// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type WorkspaceTreeSnapshot struct {
	_tab flatbuffers.Table
}

func GetRootAsWorkspaceTreeSnapshot(buf []byte, offset flatbuffers.UOffsetT) *WorkspaceTreeSnapshot {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &WorkspaceTreeSnapshot{}
	x.Init(buf, n+offset)
	return x
}

func FinishWorkspaceTreeSnapshotBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsWorkspaceTreeSnapshot(buf []byte, offset flatbuffers.UOffsetT) *WorkspaceTreeSnapshot {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &WorkspaceTreeSnapshot{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedWorkspaceTreeSnapshotBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *WorkspaceTreeSnapshot) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *WorkspaceTreeSnapshot) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *WorkspaceTreeSnapshot) Version() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *WorkspaceTreeSnapshot) MutateVersion(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *WorkspaceTreeSnapshot) SessionId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *WorkspaceTreeSnapshot) Tabs(obj *TabNode, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *WorkspaceTreeSnapshot) TabsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *WorkspaceTreeSnapshot) ActiveTabId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func WorkspaceTreeSnapshotStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func WorkspaceTreeSnapshotAddVersion(builder *flatbuffers.Builder, version uint64) {
	builder.PrependUint64Slot(0, version, 0)
}
func WorkspaceTreeSnapshotAddSessionId(builder *flatbuffers.Builder, sessionId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(sessionId), 0)
}
func WorkspaceTreeSnapshotAddTabs(builder *flatbuffers.Builder, tabs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(tabs), 0)
}
func WorkspaceTreeSnapshotStartTabsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func WorkspaceTreeSnapshotAddActiveTabId(builder *flatbuffers.Builder, activeTabId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(activeTabId), 0)
}
func WorkspaceTreeSnapshotEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
